### ISSUE TITLE
Cell merging

### ISSUE THREAD

**Issue by lvyandev** [caduandrade/davi_flutter#40]
I've compared almost all the data table in pub, none of them have cell merging feature.
I wonder is this feature feasible?
<img width="271" alt="image" src="https://user-images.githubusercontent.com/18045999/177243190-50a55f8e-226e-4c7f-b1c7-edb47b44ce16.png">

**Comment by caduandrade** [comment]
Hi @lvyandev ! This improvement is in the planning.

**Comment by caduandrade** [comment]
Requires #42

**Comment by caduandrade** [comment]
Hi @lvyandev ! 

Do you expect to use cell sorting and merging in the same table?

There are some usability issues regarding sorting in these cases. It gets worse considering that it would be possible to make a cell occupy more than one column.

Since a cell can span more than one column and row, it gets a bit awkward to use the current API that builds the data based on rows. In this scenario, the data should be more column and row independent. They would just be independent cells. In that case, again, it wouldn't make sense to have ordering.

I'm telling this whole story because I'm thinking about forking this project into another one focused more on cell vision. I believe it would be better for a cell merge.

**Comment by lvyandev** [comment]
It doesn't matter, feel free to do the change.

**Comment by u-sour** [comment]
Hi, @caduandrade is this feature available yet?

**Comment by caduandrade** [comment]
Guys, sorry for the delay. I know this feature is long awaited but also very complex because it conflicts with almost everything that already exists. I'm working on a significant performance improvement and at the same time already thinking about how to make cell merge viable.

**Comment by u-sour** [comment]
Thank you for the information, @caduandrade. I wait for this feature. If this feature is implemented, this package would be great because most of all packages in pub don't have this feature.

**Comment by caduandrade** [comment]
Starting, better late than never... It will be impossible to avoid inconsistencies, the developer will need to pay attention to this. Ex.: ordering may generate collision. In this case I will try to create custom handlers but other inconsistencies should be the developer's concern.

**Comment by caduandrade** [comment]
I expected it to be complex but it was more than I expected :smile:. One more for the next version 4.0.0.

**Comment by caduandrade** [comment]
All "done" in 4.0.0.
I'm in the experimentation/testing/updating demo phase.

Now I'm facing the following use case: last row of the model with rowSpan > 1. Until now, the code was throwing an error, but I realized that this is an acceptable situation that can occur depending on the column ordering. I believe that the only option will be to draw this last cell in half (part of the span will be hidden outside the table). If anyone has any suggestions, just comment...

**Comment by u-sour** [comment]
@caduandrade Glad to hear that. I haven't tested it yet. I'll test it later when I'm free. Thanks.

**Comment by caduandrade** [comment]
Version 4.0.0 released
