### ISSUE TITLE
Display more than one line of Text in one Cell

### ISSUE THREAD

**Issue by lukasdeterts** [caduandrade/davi_flutter#70]
First of all: nice Work, I love this package and it's nice to work with

It would be nice, if we can add line breaks or paragraphs to a cell to write more text in it so we can make small lists inside the table.

**Comment by caduandrade** [comment]
Hi @lukasdeterts! Thanks!

The `stringValue` is just a quick way to create a text cell and its default ordering. In this case, I suggest using `cellBuilder` to create any content. It could be a Column with N strings.

The problem is that for performance reasons (the same as indicated by the `ListView`), the cell height is always fixed. So you would have to set a height for the largest existing column in the model. And the other smaller cells will stay at the same time :disappointed: 

It is on my list to implement dynamic height (it will only be suitable for templates with paginated or small content).

**Comment by lukasdeterts** [comment]
Thanks for your reply! I understand the issues.
How do I set a height for the whole model? i searched a bit and sadly i did not fiund the way to go..

**Comment by caduandrade** [comment]
I'm sorry. I need to add this example in the `README`.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: DaviTheme(
            data: const DaviThemeData(
                cell: CellThemeData(
                    contentHeight: 48,
                    alignment: Alignment.topLeft,
                    padding: EdgeInsets.all(8))),
            child: Davi<Person>(_model)));
  }
```
