### ISSUE TITLE
Rebuilding only a row

### ISSUE THREAD

**Issue by vauradkar** [caduandrade/davi_flutter#98]
Is it possible to rebuild only a row? The use case is that the cell is getting updated and it affects contents/theme of cells in its row but also in the neighboring row. This is kind of forcing me to refresh the entire [large] grid - making it very sluggish. Wondering if I can somehow rebuild affected rows only.

**Comment by caduandrade** [comment]
Hi @vauradkar!

I'm addressing all the performance improvements for version 4 that I'm currently working on. In this version, the model data continues to represent a row, but the internal layout is in grid format to allow merging. On the other hand, it's much more performant because primitive values ​​will be painted directly by the layout and no longer created internal widgets.

Let me know what exactly is happening to you to perhaps improve performance even more in version 4. Do you change a value in the model and then rebuild the table? What's so slow? The table rebuild or the scroll? Are you mapping your data to primitive values ​​or creating your own widget for the cell?

**Comment by vauradkar** [comment]
> Do you change a value in the model and then rebuild the table?

Yes. To take  "Employee database", Basically rows representemployees in the table. The right to the table is "employee details" which contain more data than whats in the table. When I click a celll, employee related details get loaded in widget in the side. A user can either choose to edit the values in the table or choose to use "details widget" to edit the values.
<img width="1275" alt="Screenshot 2024-11-24 at 4 56 07 PM" src="https://github.com/user-attachments/assets/d22eca06-c43a-4ab1-8494-b3184f3ac3e9">

> What's so slow? The table rebuild or the scroll? 

Repaint during scroll. ~100 rows 15 columns. Details contain 25 fields. Of those around 10 fields share `TextEditingController` with a current selected row in the table. Here is profile data. Tried couple of things from the link in the screenshot but nothing worked.
![Screenshot 2024-11-24 at 4 33 45 PM](https://github.com/user-attachments/assets/5e4ab104-76a2-4bde-bb4b-5e0396b698f2)


> Are you mapping your data to primitive values ​​or creating your own widget for the cell?

Creating widgets through cell builder. Each cell in the table is a TextField which is backed by a `TextEditingController` which is shared with the text field in "details widget".

**Comment by caduandrade** [comment]
Hi @vauradkar!

Version 4 makes better use of internal keys, but building your own Widget for the cell will always be more inefficient. Even worse when it is a `TextField`.

As a solution in version 4, I intend to make the concept of an editable cell available, but where the developer does not create the TextField. The table itself would manage it. But the difference is that there would not be several in memory at the same time. When clicking on an editable cell, it turns into a `TextField`. When you lose focus, it goes back to being just a text cell. I believe this is the solution, and if you don't want to wait for the new version, maybe you can try to do something similar.

Maybe you would be a great test case for this new version :smile: . Do you use any special theme configuration in your `TextField`?
